name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path:  # the path to the log file
    description: 'The path of the log file'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
